import './globals.css'
//import 'tailwindcss/tailwind.css'

import NavBarOld from './components/navBar/NavBar-old'
import NavBar from './components/navBar/NavBar'

import { Inter } from 'next/font/google'

import {uesEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
<head>
<title>Majestic 7 Guesthouse </title>
</head>
<body className='text-gray-600 font-body'>
<header>

</header>
<nav>
<NavBar/>
</nav> 
<h2></h2>   
        {children}</body>
    </html>
  )
}
