import './globals.css'
//import 'tailwindcss/tailwind.css'

import NavBar from './components/navBar/NavBar'
import { Inter } from 'next/font/google'

import {uesEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">

      <body className='text-gray-600 font-body'>
        <div className='grid md:grid-cols-3'> {/*<!-- content wrapper-->*/}
        <div className='md:col-span-1 md:flex md:justify-end'>

        <NavBar />
        </div>{/*<!-- end nav wrapper-->*/}

        <main className="px-16 py-6 md:col-span-2" >

          <div className='flex justify-center md:justify-end'>
          <a href="#" className='text-primary btn border-primary md:border-2 hover:bg-primary hover:text-white'>Log in</a>
            <a href="#" className='ml-2 btn border-primary md:border-2 hover:bg-primary hover:text-white'>Sign up</a>
          </div>

          <header>
            <h2> h2 header</h2>
            <h3> h3 header</h3>
          </header>

          {/*hero*/}
          <div>
          <img src="/images/TST-peninsula.jpg" alt= "" className ="w-full" />
          <div>hero title</div>
          <div>hero subtitle</div>
          <div> button</div>
          </div>
          <div>
          <section className='px-16 py-y bg-gray-500'>
            <div>
              <h2 className="text-grey-700 text-6xl font-semibold"> stay with us</h2>
              <h3 className="text-2xl font-semibold" > come experience the vibe of Tsim Sha Tsui</h3>
            </div>
          <div>
            <h4 className='font-bold mt-4 pb-2 border-b border-gray-200'>What we offer</h4>
            <div className='mt-8 grid lg:grid-cols-3 gap-10' >
              {/* cards go here*/}

              <div className='card' >
                <img src="/images/rooms-placeholder.jpeg" alt ="" className='w-full h-32 sm:h-48 object-cover'/>
                  <div className='m-4'>
                    <span className='font-bold'>card title</span>
                    <span className='block text-gray-500 text-sm'> card text</span>
                  </div>
              </div>
              <div className='card' >
                <img src="/images/rooms-placeholder.jpeg" alt ="" className='w-full h-32 sm:h-48 object-cover'/>
                  <div className='m-4'>
                    <span className='font-bold'>card title</span>
                    <span className='block text-gray-500 text-sm'> card text</span>
                  </div>
              </div>
              <div className='card' >
                <img src="/images/rooms-placeholder.jpeg" alt ="" className='w-full h-32 sm:h-48 object-cover'/>
                  <div className='m-4'>
                    <span className='font-bold'>card title</span>
                    <span className='block text-gray-500 text-sm'> card text</span>
                  </div>
                  <div className='card' >
                <img src="/images/rooms-placeholder.jpeg" alt ="" className='w-full h-32 sm:h-48 object-cover'/>
                  <div className='m-4'>
                    <span className='font-bold'>card title</span>
                    <span className='block text-gray-500 text-sm'> card text</span>
                  </div>
              </div>
              </div>
            </div>

          </div>
          </section>
          </div>
        </main>
      </div>
        
        {children}
        

        </body>
    </html>
  )
}
