spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/majestic
    username: majestic
    password: majestic
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
